apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-fe
  labels:
    app: my-app-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-fe
  template:
    metadata:
      labels:
        app: my-app-fe
    spec:
      containers:
      - name: udagram-frontend
        image: danotsonof/udagram_frontend
        ports:
        - containerPort: 80